version: '3.9'

x-environment: &kafka-cluster-environments
  # KRaft settings
  KAFKA_KRAFT_CLUSTER_ID: z6sXmGHyR1qVTyyl9XXr0g
  KAFKA_CFG_PROCESS_ROLES: controller,broker
  KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka-0:9093,1@kafka-1:9093,2@kafka-2:9093
  # Listener settings

  KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
  KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://:9092
  KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
  KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
  KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT

  # Cluster settings
  KAFKA_CFG_DEFAULT_REPLICATION_FACTOR: 3
  KAFKA_CFG_MIN_INSYNC_REPLICAS: 2
  KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
  KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
  KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR: 2

services:
  kafka-0:
    image: bitnami/kafka:3.7
    ports:
      - "9094:9094"
    environment:
      KAFKA_CFG_NODE_ID: 0
      <<: *kafka-cluster-environments
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://:9092,EXTERNAL://127.0.0.1:9094
    networks:
      - kafka-network
    volumes:
      - kafka-volume-0:/bitnami

  kafka-1:
    image: bitnami/kafka:3.7
    ports:
      - "19094:9094"
    environment:
      KAFKA_CFG_NODE_ID: 1
      <<: *kafka-cluster-environments
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://:9092,EXTERNAL://127.0.0.1:19094
    networks:
      - kafka-network
    volumes:
      - kafka-volume-1:/bitnami

  kafka-2:
    image: bitnami/kafka:3.7
    ports:
      - "29094:9094"
    environment:
      KAFKA_CFG_NODE_ID: 2
      <<: *kafka-cluster-environments
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://:9092,EXTERNAL://127.0.0.1:29094
    networks:
      - kafka-network
    volumes:
      - kafka-volume-2:/bitnami

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "9090:8080"
    depends_on:
      - kafka-0
      - kafka-1
      - kafka-2
    environment:
      - KAFKA_CLUSTERS_0_NAME=KRaft Cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-0:9092,kafka-1:9092,kafka-2:9092
      - DYNAMIC_CONFIG_ENABLED=true
      - KAFKA_CLUSTERS_0_AUDIT_TOPICAUDITENABLED=true
      - KAFKA_CLUSTERS_0_AUDIT_CONSOLEAUDITENABLED=true
    networks:
      - kafka-network

volumes:
  kafka-volume-0:
    driver: local
  kafka-volume-1:
    driver: local
  kafka-volume-2:
    driver: local

networks:
  kafka-network:
    driver: bridge
